#!/bin/bash

function usage {
    echo "Usage: $0 [--debug] [--debugMaven]"
    exit 1
}

debug=0
debugMaven=0
unknown_option=0
while true ; do
    case "$1" in
        --debug) debug=1; shift;;
        --debugMaven) debugMaven=1; shift;;
	-*) echo "Unknown option $1"; unknown_option=1; shift;;
	*) break ;;
    esac
done

if [ "${unknown_option}" == "1" ]; then
    usage
    exit 1
fi

rm -rf mavenlog.log
#mvn -Dmaven.repo.local=$PWD/.m2repo -U -s ~/.m2/localreleasesettings.xml -DincludesList='org.opendaylight.*' -Pstagingrepodir -B versions:use-latest-versions -X -l mavenlog.log
mvncmd="mvn"
if [ ${debug} == 1 ]; then
    mvncmd="mvnDebug"
fi

mvnDebugOpts=""
if [ ${debugMaven} == 1 ]; then
    mvnDebugOpts="-X -l mavenlog.log"
fi

${mvncmd} -Dmaven.repo.local=$PWD/.m2repo -U -s ~/.m2/localreleasesettings.xml -Dincludes='org.opendaylight*' -Pstagingrepodir -B org.codehaus.mojo:versions-maven-plugin:2.2-gmeo-SNAPSHOT:use-latest-versions ${mvnDebugOpts}
